apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "timour.miagol@gmail.com" # eigene mail mit gmail, wie in Jenkins !
  GMAIL_PASSWORD: "pdvb eodb eooo wunz"     # vorher einstlelen !
type: Opaque

# Passw0rd@1234